### ISSUE TITLE
Dockerfile for test_segmentation engine needs to refer to specific version and not master

### ISSUE THREAD

**Issue by ebremer** [SBU-BMI/pathomics_analysis#3]
see: https://github.com/SBU-BMI/pathomics_analysis/blob/master/nucleusSegmentation/test_segmentation/Dockerfile

**Comment by ebremer** [comment]
this is the specific line of code:
https://github.com/SBU-BMI/pathomics_analysis/blob/master/nucleusSegmentation/test_segmentation/Dockerfile#L4

**Comment by tdiprima** [comment]
According to Vincent Driessen's [article](http://nvie.com/posts/a-successful-git-branching-model/#the-main-branches):

> We consider origin/master to be the main branch where the source code of HEAD always reflects a production-ready state.

The same sentiment is echoed by other people ([example1](https://github.com/rotati/wiki/wiki/How-we-use-master,-staging-and-stable-branch-in-Github), example2 - **git-scm**, implied by [Figure 21](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)).

Keeping `master` as production-ready reduces the overhead of trying to track down every instance where you're calling a particular version.  I think the versions are basically there as milestone markers, and for rollback purposes.

Remember too that we've also got Docker instances.  "Latest" should probably follow-suit and be production-ready.

### If...
we wanted to tag everything, we would truly need a schematic drawing of what is calling what, and where, and how.  i.e. "This" script is calling "these Docker" containers, each one is at "this version".  Inside Docker container "X", however, it is building from "GitHub repository Y", version "n.n" _(or branch "blah")_.  "**Because**" blah blah blah.

We probably still need a diagram anyway, though.  Couldn't hurt.

IMHO

**Comment by tdiprima** [comment]
@tkurc, since we are using this repository in our Quip distro, should we tag a `release` branch?

**Comment by tdiprima** [comment]
"test_segmentation engine" has been replaced by new Docker image, aptly named "pathomics_analysis".

Additionally (and actually more pertinent to this issue), Dockerfile no longer re-clones this repo from GitHub.

This issue is resolved.  Creating new issue: #8.
